[package]
name = "pve-dynamic-ipsets"
description = "Maintaining dynamic objects in PVE Firewall"
version = "1.1.3"
edition = "2021"
license = "MIT"
authors = ["chaueq"]

[dependencies]
dns-lookup = "^2.0.4"
signal-hook = "^0.3.17"
